// <auto-generated />
using System;
using Catarinense.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Catarinense.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005142919_AddFotoDuplicadaPrefixo")]
    partial class AddFotoDuplicadaPrefixo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Catarinense.Domain.Entities.EtapaItemExecucao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<bool>("Concluida")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EtapaItemPadraoId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<string>("FotoDuplicadaOriginalPrefixo")
                        .HasColumnType("longtext");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Funcionalidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("LimpezaEtapaExecucaoId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RelatoProblema")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EtapaItemPadraoId");

                    b.HasIndex("LimpezaEtapaExecucaoId");

                    b.ToTable("etapas_itens_execucao", (string)null);
                });

            modelBuilder.Entity("Catarinense.Domain.Entities.EtapaItemPadrao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("EnquadramentoFoto")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("EtapaPadraoId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EtapaPadraoId");

                    b.ToTable("etapas_itens_padrao", (string)null);
                });

            modelBuilder.Entity("Catarinense.Domain.Entities.EtapaPadrao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("LinkVideo")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Obrigatoria")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("etapas_padrao", (string)null);
                });

            modelBuilder.Entity("Catarinense.Domain.Entities.FotoEtapa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("LimpezaEtapaExecucaoId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<string>("UrlArquivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("LimpezaEtapaExecucaoId");

                    b.ToTable("fotos_etapa", (string)null);
                });

            modelBuilder.Entity("Catarinense.Domain.Entities.FotoHash", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrefixoOrigem")
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FotosHashes");
                });

            modelBuilder.Entity("Catarinense.Domain.Entities.LimpezaEtapaExecucao", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("EtapaPadraoId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<Guid>("LimpezaFinaId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<string>("ProblemaExtraDescricao")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<string>("ProblemaExtraFotoDuplicadaOriginalPrefixo")
                        .HasColumnType("longtext");

                    b.Property<string>("ProblemaExtraFotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("EtapaPadraoId");

                    b.HasIndex("LimpezaFinaId");

                    b.ToTable("limpeza_etapa_execucoes", (string)null);
                });

            modelBuilder.Entity("Catarinense.Domain.Entities.LimpezaFina", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<DateTime?>("AvaliadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("AvaliadorId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<bool>("CortinasRetiradas")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FinalizadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("IniciadaEm")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("NotificacaoEnviada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NumeroOS")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ObservacaoAvaliacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("OnibusId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroOS");

                    b.HasIndex("OnibusId");

                    b.HasIndex("OperadorId");

                    b.HasIndex("Status");

                    b.ToTable("limpezas_finas", (string)null);
                });

            modelBuilder.Entity("Catarinense.Domain.Entities.Onibus", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Placa")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Prefixo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Prefixo")
                        .IsUnique();

                    b.ToTable("onibus", (string)null);
                });

            modelBuilder.Entity("Catarinense.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)")
                        .UseCollation("ascii_bin");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("PrecisaTrocarSenha")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("TentativasFalhasLogin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Matricula")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("Catarinense.Domain.Entities.EtapaItemExecucao", b =>
                {
                    b.HasOne("Catarinense.Domain.Entities.EtapaItemPadrao", "EtapaItemPadrao")
                        .WithMany()
                        .HasForeignKey("EtapaItemPadraoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Catarinense.Domain.Entities.LimpezaEtapaExecucao", "LimpezaEtapaExecucao")
                        .WithMany("Itens")
                        .HasForeignKey("LimpezaEtapaExecucaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EtapaItemPadrao");

                    b.Navigation("LimpezaEtapaExecucao");
                });

            modelBuilder.Entity("Catarinense.Domain.Entities.EtapaItemPadrao", b =>
                {
                    b.HasOne("Catarinense.Domain.Entities.EtapaPadrao", "EtapaPadrao")
                        .WithMany("Itens")
                        .HasForeignKey("EtapaPadraoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EtapaPadrao");
                });

            modelBuilder.Entity("Catarinense.Domain.Entities.FotoEtapa", b =>
                {
                    b.HasOne("Catarinense.Domain.Entities.LimpezaEtapaExecucao", null)
                        .WithMany("Fotos")
                        .HasForeignKey("LimpezaEtapaExecucaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catarinense.Domain.Entities.LimpezaEtapaExecucao", b =>
                {
                    b.HasOne("Catarinense.Domain.Entities.EtapaPadrao", "EtapaPadrao")
                        .WithMany()
                        .HasForeignKey("EtapaPadraoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Catarinense.Domain.Entities.LimpezaFina", null)
                        .WithMany("Etapas")
                        .HasForeignKey("LimpezaFinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EtapaPadrao");
                });

            modelBuilder.Entity("Catarinense.Domain.Entities.EtapaPadrao", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Catarinense.Domain.Entities.LimpezaEtapaExecucao", b =>
                {
                    b.Navigation("Fotos");

                    b.Navigation("Itens");
                });

            modelBuilder.Entity("Catarinense.Domain.Entities.LimpezaFina", b =>
                {
                    b.Navigation("Etapas");
                });
#pragma warning restore 612, 618
        }
    }
}
